### ISSUE TITLE
Similar function signatures for Learning Curve retrieval

### ISSUE THREAD

**Issue by Neeratyoy** [automl/mf-prior-bench#1]
In my opinion, having the same function signatures for the two types of retrieval makes sense:
* `query(config: C, fidelity) -> R`: gives the point or the exact result at `fidelity`
* `trajectory(config: C, fidelity) -> List[R]`: gives the full learning curve until `fidelity`

Additionally, I was wondering if we can already have a placeholder parameter that can be further passed to either a benchmark state during initialisation or to these function calls above. That is whether the evaluation is being `continued` or `thawed`.
The only thing that should change then is the cost of continuations. Not sure where then is the best place to change. We could also kind of do it post-hoc for the evaluations made by subtracting the cost incurred for a lower fidelity evaluation. 

For the non-benchmark case, NePS anyways handles continuation so should work out fine I believe.

@DaStoll @eddiebergman thoughts?
Please feel free to take the call.

**Comment by eddiebergman** [comment]
As a note, I changed `def trajectory` to be but I see your argument none the less

```
@abstractmethod
def trajectory(
    self,
    config: C,
    *,
    frm: F = ...,
    to: F = ...,
) -> list[R]:
```

**Comment by eddiebergman** [comment]
Regarding the freeze-thaw action, it only makes sense with freeze-thawable networks, I would leave it to post-hoc for simplicity of the benchmark
